allowing multiple files

diff --git a/godo b/godo
--- a/godo
+++ b/godo
@@ -3,35 +3,44 @@
 function usage () {
 	local name=`basename $0`
 	echo "usage: $name <go-source-file>"
+	exit 1
 }
 
-if ! test -f "$1"; then
-	if test -n "$1"; then
-		echo "file not found: $1"
-	fi
+if test -z "$*"; then
 	usage
-	exit 1
 fi
 
-d="$TMPDIR/$$.$RANDOM"
-if ! mkdir $d; then
+for file in "$@"; do
+	if ! test -f "$file"; then
+		echo "file not found: $file"
+		usage
+	fi
+done
+
+TMP_GODO_DIR="$TMPDIR/$$.$RANDOM"
+if ! mkdir "$TMP_GODO_DIR"; then
 	echo "could not create temporary directory... sigh"
 	exit 1
 fi
 
-gofile=$d/tmp.go
-if test "#!" = `head -n1 "$1" | cut -c 1-2 `; then
-	sed -n '2,$p' $1 > $gofile
-else
-	cp "$1" $gofile
-fi
+SRCDIR="$TMP_GODO_DIR/src"
+mkdir "$SRCDIR"
 
-cat > $d/Makefile <<EOF
+for file in "$@"; do
+	DESTFILE="$SRCDIR/$file"
+	if test "#!" = `head -n1 "$file" | cut -c 1-2 `; then
+		sed -n '2,$p' $file > $DESTFILE
+	else
+		cp "$file" $DESTFILE
+	fi
+done
+
+cat > $TMP_GODO_DIR/Makefile <<EOF
 include \$(GOROOT)/src/Make.inc
 TARG=tmp.out
-GOFILES=$gofile
+GOFILES=$SRCDIR/*
 include \$(GOROOT)/src/Make.cmd
 EOF
 
-make --directory=$d > /dev/null && $d/tmp.out
-rm -rf $d
+make --silent --directory=$TMP_GODO_DIR && $TMP_GODO_DIR/tmp.out
+rm -rf $TMP_GODO_DIR
