allowing arguments

diff --git a/godo b/godo
--- a/godo
+++ b/godo
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 function usage () {
 	local name=`basename $0`
@@ -10,10 +10,24 @@ if test -z "$*"; then
 	usage
 fi
 
-for file in "$@"; do
-	if ! test -f "$file"; then
-		echo "file not found: $file"
-		usage
+FILES=()
+ARGS=()
+DONE_WITH_FILES=
+
+for arg in "$@"; do
+	if test "$arg" = "--"; then
+		DONE_WITH_FILES=1
+		continue
+	fi
+	
+	if test -n "$DONE_WITH_FILES"; then
+		ARGS[${#ARGS[*]}]="$arg"
+	else
+		if ! test -f "$arg"; then
+			echo "file not found: $arg"
+			usage
+		fi
+		FILES[${#FILES[*]}]="$arg"
 	fi
 done
 
@@ -26,7 +40,7 @@ fi
 SRCDIR="$TMP_GODO_DIR/src"
 mkdir "$SRCDIR"
 
-for file in "$@"; do
+for file in "${FILES[@]}"; do
 	DESTFILE="$SRCDIR/$file"
 	if test "#!" = `head -n1 "$file" | cut -c 1-2 `; then
 		sed -n '2,$p' $file > $DESTFILE
@@ -42,5 +56,5 @@ GOFILES=$SRCDIR/*
 include \$(GOROOT)/src/Make.cmd
 EOF
 
-make --silent --directory=$TMP_GODO_DIR && $TMP_GODO_DIR/tmp.out
+make --silent --directory=$TMP_GODO_DIR && $TMP_GODO_DIR/tmp.out "${ARGS[@]}"
 rm -rf $TMP_GODO_DIR
